from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()

PRIVACY_POLICY_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aithletix – Privacy Policy</title>
    <link rel="stylesheet" href="/static/styles.css">
</head>
<body>
    <div class="container">

        <div class="badge">BETA</div>
        <h1>Privacy Policy</h1>
        <p class="updated">Last updated: May 7, 2026</p>

        <div class="intro">
            This policy applies to the beta version of Aithletix distributed via Apple TestFlight
            for testing purposes only. This is not a final production privacy policy.
        </div>

        <h2>What We Collect</h2>
        <ul>
            <li><strong>Account information</strong> — Email address and display name used to create your account</li>
            <li><strong>Body metrics</strong> — Weight, height, date of birth, and biological sex you enter in the app</li>
            <li><strong>HealthKit data</strong> — Steps, active calories, and distance read from Apple Health with your permission</li>
            <li><strong>Workout data</strong> — Training sessions, exercises, sets, reps, and personal records you log</li>
            <li><strong>Weight logs</strong> — Body weight entries you record over time</li>
        </ul>

        <h2>How We Use It</h2>
        <p>
            Your data is used solely to provide app features — calculating nutrition targets, generating AI coaching
            insights, and displaying your training history. Your data is not sold, shared with advertisers,
            or used for any purpose outside the app.
        </p>

        <h2>Apple HealthKit</h2>
        <div class="healthkit-box">
            <p>Aithletix reads health data from Apple Health only to display your activity in the app.</p>
            <p>HealthKit data will not be used for advertising, will not be sold to data brokers,
            and will not be shared with third parties.</p>
        </div>

        <h2>Third-Party Services</h2>
        <ul>
            <li><strong>Supabase</strong> — Your account and workout data is stored on Supabase's servers</li>
            <li><strong>Anthropic</strong> — Coaching insights are generated by Claude AI. Relevant context
            (workout type, calorie targets) is sent to Anthropic's API to produce your insight</li>
        </ul>

        <h2>Beta Disclaimer</h2>
        <p>
            This is a test build. Data collected during testing may be deleted when the app reaches its
            production release. Do not enter sensitive personal information beyond what is needed to test the app.
        </p>

        <hr class="divider">

        <h2>Contact</h2>
        <p>
            Questions or data deletion requests:
            <a href="mailto:jesus.flores1008@gmail.com">jesus.flores1008@gmail.com</a>
        </p>

    </div>
</body>
</html>
"""


@router.get("/privacy", response_class=HTMLResponse)
def privacy_policy():
    return PRIVACY_POLICY_HTML
